import type { Job } from "./types";

export const MOCK_JOBS: Job[] = [
  {
    id: "1",
    title: "Senior Frontend Engineer",
    company: "NANSA AI",
    location: "Seoul, Gangnam",
    salary: "₩80M - ₩120M",
    tags: ["React", "Next.js", "TypeScript"],
    createdAt: "2024-03-24",
  },
  {
    id: "2",
    title: "Backend Platform Lead",
    company: "Meshcraft",
    location: "Remote",
    salary: "₩70M - ₩110M",
    tags: ["Kotlin", "Spring Boot", "PostgreSQL"],
    createdAt: "2024-03-23",
  },
  {
    id: "3",
    title: "AI Research Scientist",
    company: "DeepMind Local",
    location: "Daegu, Suseong",
    salary: "₩90M - ₩150M",
    tags: ["Python", "PyTorch", "LLM"],
    createdAt: "2024-03-22",
  },
  {
    id: "4",
    title: "UX/UI Design Director",
    company: "Pixel Studio",
    location: "Seoul, Seongdong",
    salary: "₩60M - ₩90M",
    tags: ["Figma", "UI/UX", "System Design"],
    createdAt: "2024-03-22",
  },
  {
    id: "5",
    title: "DevOps Engineer",
    company: "CloudCore",
    location: "Pangyo",
    salary: "₩65M - ₩100M",
    tags: ["AWS", "Kubernetes", "Docker"],
    createdAt: "2024-03-21",
  },
  {
    id: "6",
    title: "Product Manager (PM)",
    company: "NextLink",
    location: "Seoul, Mapo",
    salary: "₩55M - ₩85M",
    tags: ["Data Analysis", "Agile", "Strategy"],
    createdAt: "2024-03-21",
  },
  {
    id: "7",
    title: "Android Native Developer",
    company: "Toss-like App",
    location: "Seoul, Yeoksam",
    salary: "₩75M - ₩115M",
    tags: ["Kotlin", "Architecture Components"],
    createdAt: "2024-03-20",
  },
  {
    id: "8",
    title: "Security Specialist",
    company: "SecuGuard",
    location: "Incheon",
    salary: "₩80M - ₩130M",
    tags: ["Pentesting", "Network Security"],
    createdAt: "2024-03-20",
  },
  {
    id: "9",
    title: "Data Analyst",
    company: "InsightX",
    location: "Remote",
    salary: "₩50M - ₩80M",
    tags: ["SQL", "Tableau", "Statistics"],
    createdAt: "2024-03-19",
  },
  {
    id: "10",
    title: "QA Automation Lead",
    company: "GameWorld",
    location: "Seoul, Guro",
    salary: "₩60M - ₩95M",
    tags: ["Cypress", "Selenium", "Jest"],
    createdAt: "2024-03-19",
  },
  {
    id: "11",
    title: "Solutions Architect",
    company: "Global Tech",
    location: "Pangyo",
    salary: "₩100M - ₩160M",
    tags: ["Architecture", "B2B", "SaaS"],
    createdAt: "2024-03-18",
  },
  {
    id: "12",
    title: "Junior Fullstack Dev",
    company: "Dynamic Up",
    location: "Seoul, Songpa",
    salary: "₩45M - ₩60M",
    tags: ["Node.js", "React", "MongoDB"],
    createdAt: "2024-03-18",
  },
];
